### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by ma0shu** [squiglink/server#1]
![image](https://github.com/user-attachments/assets/9a2a07ac-4e3b-4d41-8a9e-179c3272dec7)
![image](https://github.com/user-attachments/assets/0611307c-875f-4a52-99f7-302968f8f3ee)
localhost:3000 got response 404

**Comment by snacks02** [comment]
Hi!

Sorry for the late reply (didn't have notifications turned on).

This project is not complete at the moment, so unless you know what to do, it's not recommended to be used yet.

I'll be updating the documentation over time, so please check this repo in a couple months when it is more ready.
